name: app_weather_merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: setup pnpm and install dependencies
        with:
          version: 10
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
      - name: test
        run: echo "none for now"
      - name: build
        run: pnpm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: deploy to Firebase production
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRAISETOMPANE_APP_WEATHER }}'
          channelId: live
          projectId: praisetompane-app-weather
